name: flappy_dash
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.23.0
  flame_bloc: ^1.12.6
  equatable: ^2.0.7
  flutter_bloc: ^9.0.0
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/background/

  fonts:
    - family: Chewy
      fonts:
        - asset: assets/fonts/Chewy-Regular.ttf
