name: flappy_dash
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.23.0
  flame_bloc: ^1.12.6
  equatable: ^2.0.7
  flutter_bloc: ^9.0.0
  flutter_animate: ^4.5.2
  flutter_soloud: ^2.1.7
  get_it: ^8.0.3
  nakama: ^1.2.0
  flutter_svg: ^2.0.17
  android_id: ^0.4.0
  device_info_plus: ^11.3.0
  shared_preferences: ^2.5.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/background/
    - assets/audio/
    - assets/icons/

  fonts:
    - family: Chewy
      fonts:
        - asset: assets/fonts/Chewy-Regular.ttf
