// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdtcJ3QzrjXt7Vk3mNn3q6750egVDOXhY',
    appId: '1:58903924540:web:208b776965b8aed7b89839',
    messagingSenderId: '58903924540',
    projectId: 'chatapp-b5d93',
    authDomain: 'chatapp-b5d93.firebaseapp.com',
    storageBucket: 'chatapp-b5d93.appspot.com',
    measurementId: 'G-ZF05V8257W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbhFQ3nWwhszLxDYcxZl4DZqDtk3oY384',
    appId: '1:58903924540:android:2f98427402254da3b89839',
    messagingSenderId: '58903924540',
    projectId: 'chatapp-b5d93',
    storageBucket: 'chatapp-b5d93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYeuv1XnIL-Xp3Cbc2bTFMweFSxF0NtZQ',
    appId: '1:58903924540:ios:1db9ad92f3d9998bb89839',
    messagingSenderId: '58903924540',
    projectId: 'chatapp-b5d93',
    storageBucket: 'chatapp-b5d93.appspot.com',
    iosBundleId: 'com.example.flutterLearning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYeuv1XnIL-Xp3Cbc2bTFMweFSxF0NtZQ',
    appId: '1:58903924540:ios:ea3b46e525393808b89839',
    messagingSenderId: '58903924540',
    projectId: 'chatapp-b5d93',
    storageBucket: 'chatapp-b5d93.appspot.com',
    iosBundleId: 'com.example.flutterLearning.RunnerTests',
  );
}
